apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-java-server
spec:
  selector:
    matchLabels:
      app: performance-java-server
  replicas: 3
  template:
    metadata:
      labels:
        app: performance-java-server
    spec:
      containers:
        - name: performance-java-server
          image: ghcr.io/willschipp/performance-java-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
