apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: performance-java-server
  labels:
    app: performance-java-server
spec:
  source:
    type: Git
    git:
      uri: https://github.com/willschipp/performance-java-app
    contextDir: performance-java-server
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: performance-java-app:latest
